<template>
  <q-dialog v-model="show" persistent>
    <q-card style="width: 760px; max-width: 95vw">
      <q-form @submit="save">
        <q-card-section class="row items-center">
          <div class="text-h6">{{ customer ? 'Edit customer' : 'New customer' }}</div>
          <q-space />
          <q-btn flat round dense icon="close" v-close-popup aria-label="Close" />
        </q-card-section>
        <q-card-section class="q-pt-none">
          <q-banner v-if="!customer && reference.cifSource === 'CMS_GENERATED'" dense rounded class="bg-blue-grey-1 text-dark q-mb-md">
            <template #avatar><q-icon name="pin" color="primary" /></template>
            The CIF is generated by the CMS when you save.
          </q-banner>
          <DynamicForm :fields="fields" :model-value="form" :editing="!!customer" />
        </q-card-section>
        <q-card-actions align="right" class="q-pa-md">
          <q-btn flat no-caps label="Cancel" v-close-popup />
          <q-btn type="submit" unelevated no-caps color="primary" :loading="busy"
                 :label="customer ? 'Save changes' : 'Create customer'" />
        </q-card-actions>
      </q-form>
    </q-card>
  </q-dialog>
</template>

<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { Notify } from 'quasar'
import DynamicForm from './DynamicForm.vue'
import { api } from '../lib/api.js'
import { loadReference, options, reference } from '../lib/reference.js'
import { label } from '../lib/format.js'

const props = defineProps({
  modelValue: Boolean,
  customer: { type: Object, default: null }
})
const emit = defineEmits(['update:modelValue', 'saved'])

const show = computed({ get: () => props.modelValue, set: v => emit('update:modelValue', v) })
const busy = ref(false)
const form = reactive({})

const EMPTY = {
  customerRef: '', customerType: 'INDIVIDUAL', segmentCode: null, fullName: '', embossingName: '',
  nationalId: '', dateOfBirth: '', mobile: '', email: '', address: ''
}

watch(() => props.modelValue, open => {
  if (!open) return
  loadReference()
  const c = props.customer
  Object.assign(form, EMPTY, c ? {
    customerRef: c.customerRef, customerType: c.customerType, segmentCode: c.segmentCode, fullName: c.fullName,
    embossingName: c.embossingName, nationalId: c.nationalId || '', dateOfBirth: c.dateOfBirth || '',
    mobile: c.mobile || '', email: c.email || '', address: c.address || ''
  } : {})
}, { immediate: true })

// suggest the embossing name from the full name while the operator has not typed their own
const suggest = n => (n || '').toUpperCase().replace(/[^A-Z .\-/]/g, '').replace(/\s+/g, ' ').trim().slice(0, 26)
watch(() => form.fullName, (n, old) => {
  if (!form.embossingName || form.embossingName === suggest(old)) form.embossingName = suggest(n)
})

const segmentOptions = computed(() => {
  const list = options(reference.segments, s => s.name)
  // an inactive segment already on the customer stays selectable
  if (props.customer && !list.some(o => o.value === props.customer.segmentCode)) {
    list.push({ label: `${props.customer.segmentCode} (inactive)`, value: props.customer.segmentCode })
  }
  return list
})

const fields = computed(() => [
  {
    name: 'customerRef', label: 'CIF', mono: true, lockedOnEdit: true,
    required: reference.cifSource === 'CORE_BANKING',
    visible: () => !!props.customer || reference.cifSource !== 'CMS_GENERATED',
    hint: props.customer ? 'CIF cannot change' : reference.cifSource === 'EITHER' ? 'Core banking CIF, or leave blank to generate' : 'Core banking CIF',
    rules: [v => !v || /^[A-Za-z0-9-]{1,64}$/.test(v) || 'Letters, digits and - only']
  },
  { name: 'customerType', label: 'Customer type', type: 'select', required: true, options: reference.customerTypes.map(t => ({ label: label(t), value: t })) },
  { name: 'segmentCode', label: 'Segment', type: 'select', required: true, options: segmentOptions.value, hint: 'Decides which card products are allowed' },
  { name: 'fullName', label: 'Full name', required: true, maxlength: 128, col: 'col-12 col-sm-6' },
  {
    name: 'embossingName', label: 'Name on card', required: true, uppercase: true, maxlength: 26, mono: true,
    hint: 'Max 26: letters, space . - /',
    rules: [v => /^[A-Za-z .\-/]{1,26}$/.test(v || '') || 'Letters, space . - / only, max 26']
  },
  { name: 'nationalId', label: 'National ID', maxlength: 32, mono: true },
  { name: 'dateOfBirth', label: 'Date of birth', type: 'date' },
  { name: 'mobile', label: 'Mobile', maxlength: 20, rules: [v => !v || /^\+?[0-9 ]{6,20}$/.test(v) || 'Digits, spaces, leading +'] },
  { name: 'email', label: 'Email', maxlength: 128, rules: [v => !v || /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v) || 'Not a valid email'] },
  { name: 'address', label: 'Address', type: 'textarea', maxlength: 256, col: 'col-12' }
])

async function save () {
  busy.value = true
  const body = { ...form, dateOfBirth: form.dateOfBirth || null }
  try {
    const saved = props.customer
      ? await api.put(`/admin/customers/${props.customer.id}`, body)
      : await api.post('/admin/customers', body)
    Notify.create({ type: 'positive', message: props.customer ? 'Customer updated' : `Customer ${saved.customerRef} created` })
    emit('saved', saved)
    show.value = false
  } catch { /* shown */ } finally {
    busy.value = false
  }
}
</script>
