<template>
  <q-dialog v-model="show" persistent>
    <q-card style="width: 520px; max-width: 95vw">
      <q-form @submit="save">
        <q-card-section class="row items-center">
          <div>
            <div class="text-h6">Open account</div>
            <div class="text-body2 muted">{{ customer?.fullName }} · CIF {{ customer?.customerRef }}</div>
          </div>
          <q-space />
          <q-btn flat round dense icon="close" v-close-popup aria-label="Close" />
        </q-card-section>

        <q-card-section class="q-pt-none q-gutter-md">
          <q-select v-model="form.accountTypeCode" :options="typeOptions" emit-value map-options outlined dense
                    label="Account type *" :rules="[v => !!v || 'Choose an account type']" />

          <q-select v-model="form.currencyCode" :options="currencyOptions" emit-value map-options outlined dense
                    label="Currency *" :disable="!type" :rules="[v => !!v || 'Choose a currency']"
                    :hint="type ? `Currencies offered for ${type.name}` : ''" />

          <q-input v-if="type?.numberSource === 'CORE_BANKING'" v-model="form.accountNumber" outlined dense
                   label="Core banking account number *" input-class="mono" maxlength="34"
                   :rules="[v => /^[A-Za-z0-9]{4,34}$/.test(v || '') || '4-34 letters or digits']" />
          <q-banner v-else-if="type" dense rounded class="bg-blue-grey-1 text-dark">
            <template #avatar><q-icon name="pin" color="primary" /></template>
            The account number is generated by the CMS (sequence {{ type.sequenceCode }}).
          </q-banner>

          <div v-if="type?.maxPerCustomer" class="text-caption muted">
            Limit: {{ type.maxPerCustomer }} open {{ type.name.toLowerCase() }}(s) per customer.
          </div>
        </q-card-section>

        <q-card-actions align="right" class="q-pa-md">
          <q-btn flat no-caps label="Cancel" v-close-popup />
          <q-btn type="submit" unelevated no-caps color="primary" label="Open account" :loading="busy" />
        </q-card-actions>
      </q-form>
    </q-card>
  </q-dialog>
</template>

<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { Notify } from 'quasar'
import { api } from '../lib/api.js'
import { loadReference, reference } from '../lib/reference.js'

const props = defineProps({
  modelValue: Boolean,
  customer: { type: Object, default: null }
})
const emit = defineEmits(['update:modelValue', 'saved'])

const show = computed({ get: () => props.modelValue, set: v => emit('update:modelValue', v) })
const busy = ref(false)
const form = reactive({ accountTypeCode: null, currencyCode: null, accountNumber: '' })

watch(() => props.modelValue, open => {
  if (!open) return
  loadReference(true)
  Object.assign(form, { accountTypeCode: null, currencyCode: null, accountNumber: '' })
})

const type = computed(() => reference.accountTypes.find(t => t.code === form.accountTypeCode))
const typeOptions = computed(() => reference.accountTypes.map(t => ({
  label: `${t.name} (${t.code})`, value: t.code,
  caption: t.numberSource === 'CORE_BANKING' ? 'Number from core banking' : 'Number generated by CMS'
})))
const currencyOptions = computed(() => reference.currencies
  .filter(c => type.value?.currencies.includes(c.code))
  .map(c => ({ label: `${c.code} – ${c.name}`, value: c.code })))

watch(() => form.accountTypeCode, () => {
  if (!currencyOptions.value.some(o => o.value === form.currencyCode)) {
    form.currencyCode = currencyOptions.value.length === 1 ? currencyOptions.value[0].value : null
  }
})

async function save () {
  busy.value = true
  try {
    const a = await api.post(`/admin/customers/${props.customer.id}/accounts`, {
      accountTypeCode: form.accountTypeCode,
      currencyCode: form.currencyCode,
      accountNumber: type.value?.numberSource === 'CORE_BANKING' ? form.accountNumber : null
    })
    Notify.create({ type: 'positive', message: `Account ${a.accountNumber} opened` })
    emit('saved', a)
    show.value = false
  } catch { /* shown */ } finally {
    busy.value = false
  }
}
</script>
