<template>
  <RefCrudPage title="Account types" noun="account type" endpoint="/admin/setup/account-types"
               subtitle="Per type: where the account number comes from, which currencies are offered, and how many a customer may hold."
               :columns="columns" :fields="fields" :defaults="defaults" :usage-note="usage"
               :cell-slots="['numberSource', 'currencies']">
    <template #cell-numberSource="{ row }">
      <q-badge outline :color="row.numberSource === 'CORE_BANKING' ? 'info' : 'primary'"
               :label="row.numberSource === 'CORE_BANKING' ? 'Core banking' : `CMS · ${row.sequenceCode}`" />
    </template>
    <template #cell-currencies="{ row }">
      <q-chip v-for="c in row.currencies" :key="c" dense square size="sm" :label="c" />
    </template>
  </RefCrudPage>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import RefCrudPage from '../../components/RefCrudPage.vue'
import { api } from '../../lib/api.js'

const currencies = ref([])
const sequences = ref([])

onMounted(async () => {
  [currencies.value, sequences.value] = await Promise.all([
    api.get('/admin/setup/currencies'), api.get('/admin/setup/number-sequences')])
})

const columns = [
  { name: 'code', label: 'Code', field: 'code', align: 'left', sortable: true, classes: 'mono' },
  { name: 'name', label: 'Name', field: 'name', align: 'left', sortable: true },
  { name: 'ledgerMode', label: 'Balance held in', field: 'ledgerMode', align: 'left', format: v => v === 'CORE_BANKING' ? 'Core banking' : 'CMS ledger' },
  { name: 'numberSource', label: 'Account number', field: 'numberSource', align: 'left' },
  { name: 'currencies', label: 'Currencies', field: 'currencies', align: 'left' },
  { name: 'maxPerCustomer', label: 'Max / customer', field: 'maxPerCustomer', align: 'right', format: v => v ?? 'No limit' },
  { name: 'accounts', label: 'Accounts', field: 'accounts', align: 'right', sortable: true },
  { name: 'active', label: 'Status', field: 'active', align: 'left' }
]

const fields = computed(() => [
  { name: 'code', label: 'Code', required: true, uppercase: true, maxlength: 16, mono: true, lockedOnEdit: true,
    hint: 'A-Z, 0-9, _ · cannot change later', rules: [v => /^[A-Z0-9_]{1,16}$/.test(v || '') || 'A-Z, 0-9, _ only'] },
  { name: 'name', label: 'Name', required: true, maxlength: 64 },
  { name: 'ledgerMode', label: 'Balance held in', type: 'select', required: true,
    options: [{ label: 'CMS ledger', value: 'CMS_LEDGER' }, { label: 'Core banking', value: 'CORE_BANKING' }],
    hint: 'Where the authorisation engine checks funds' },
  { name: 'numberSource', label: 'Account number source', type: 'select', required: true,
    options: [{ label: 'Generated by CMS', value: 'CMS_GENERATED' }, { label: 'Entered from core banking', value: 'CORE_BANKING' }] },
  { name: 'sequenceCode', label: 'Number sequence', type: 'select', required: true,
    visible: m => m.numberSource === 'CMS_GENERATED',
    options: sequences.value.filter(s => s.code !== 'CIF').map(s => ({ label: `${s.code} · next ${s.nextNumber}`, value: s.code })),
    hint: 'Manage sequences under Numbering & settings' },
  { name: 'maxPerCustomer', label: 'Max open accounts per customer', type: 'number', hint: 'Blank = no limit',
    rules: [v => v === null || v === '' || v >= 1 || 'At least 1'] },
  { name: 'currencies', label: 'Currencies offered', type: 'multiselect', required: true, col: 'col-12',
    options: currencies.value.filter(c => c.active).map(c => ({ label: `${c.code} – ${c.name}`, value: c.code })) },
  { name: 'description', label: 'Description', type: 'textarea', maxlength: 256, col: 'col-12' },
  { name: 'active', label: 'Active (can be opened)', type: 'toggle', col: 'col-12' }
])

const defaults = () => ({
  code: '', name: '', description: '', ledgerMode: 'CMS_LEDGER', numberSource: 'CMS_GENERATED',
  sequenceCode: 'ACCOUNT', maxPerCustomer: null, currencies: [], active: true
})
const usage = t => t.accounts > 0 ? `${t.accounts} account(s) of this type exist. Changes apply to new accounts only.` : ''
</script>
