<template>
  <RefCrudPage ref="crud" title="Numbering & settings" noun="number sequence" endpoint="/admin/setup/number-sequences"
               subtitle="Formats for CMS-generated CIF and account numbers. Number = prefix + zero-padded value (+ Luhn digit)."
               :columns="columns" :fields="fields" :defaults="defaults" :cell-slots="['nextNumber']">
    <template #top>
      <q-card flat bordered class="q-mb-md">
        <q-card-section>
          <div class="text-subtitle1 text-weight-medium">Customer CIF source</div>
          <div class="text-body2 muted q-mb-sm">How the CIF is set when a customer is created.</div>
          <q-option-group v-model="cifSource" :options="cifOptions" color="primary" :disable="!can.supervise" @update:model-value="saveCif" />
        </q-card-section>
      </q-card>
      <q-card v-if="freeSettings.length" flat bordered class="q-mb-md">
        <q-card-section>
          <div class="text-subtitle1 text-weight-medium">Institution and risk settings</div>
          <div class="text-body2 muted q-mb-md">Used by fraud rules and fees. Changes need a supervisor's approval.</div>
          <div class="row q-col-gutter-md">
            <div v-for="s in freeSettings" :key="s.key" class="col-12 col-md-6">
              <q-input v-model="s.edit" outlined dense :label="s.key" :hint="s.description + (s.hint ? ' · ' + s.hint : '')"
                       :readonly="!can.supervise" :rules="[v => new RegExp('^(' + s.pattern + ')$').test(v || '') || s.hint]">
                <template #append>
                  <q-btn v-if="can.supervise && s.edit !== s.value" flat dense no-caps color="primary" label="Save" @click="saveSetting(s)" />
                </template>
              </q-input>
            </div>
          </div>
        </q-card-section>
      </q-card>
    </template>
    <template #cell-nextNumber="{ row }">
      <span class="mono text-weight-medium">{{ row.nextNumber }}</span>
    </template>
  </RefCrudPage>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { Notify } from 'quasar'
import RefCrudPage from '../../components/RefCrudPage.vue'
import { api, pending } from '../../lib/api.js'
import { can } from '../../lib/session.js'
import { reloadReference } from '../../lib/reference.js'

const crud = ref(null)
const cifSource = ref(null)
const freeSettings = ref([])

function setSettings (s) {
  cifSource.value = s.find(x => x.key === 'cif.source')?.value
  freeSettings.value = s.filter(x => x.pattern).map(x => ({ ...x, edit: x.value }))
}

async function saveSetting (s) {
  try {
    const res = await api.put(`/admin/setup/settings/${s.key}`, { value: s.edit })
    if (!pending(res)) Notify.create({ type: 'positive', message: `${s.key} updated` })
  } catch { /* shown */ }
  setSettings(await api.get('/admin/setup/settings'))
}
const cifOptions = [
  { label: 'Generated by the CMS (CIF sequence)', value: 'CMS_GENERATED' },
  { label: 'Entered from core banking (required)', value: 'CORE_BANKING' },
  { label: 'Either: entered, or generated when left blank', value: 'EITHER' }
]

onMounted(async () => {
  setSettings(await api.get('/admin/setup/settings'))
})

async function saveCif (v) {
  try {
    const res = await api.put('/admin/setup/settings/cif.source', { value: v })
    if (pending(res)) {
      const s = await api.get('/admin/setup/settings')
      cifSource.value = s.find(x => x.key === 'cif.source')?.value
      return
    }
    Notify.create({ type: 'positive', message: 'CIF source updated' })
    reloadReference().catch(() => {})
  } catch {
    const s = await api.get('/admin/setup/settings')
    cifSource.value = s.find(x => x.key === 'cif.source')?.value
  }
}

const columns = [
  { name: 'code', label: 'Code', field: 'code', align: 'left', sortable: true, classes: 'mono' },
  { name: 'name', label: 'Name', field: 'name', align: 'left' },
  { name: 'prefix', label: 'Prefix', field: 'prefix', align: 'left', classes: 'mono', format: v => v || '—' },
  { name: 'bodyLength', label: 'Digits', field: 'bodyLength', align: 'right' },
  { name: 'checkDigit', label: 'Check digit', field: 'checkDigit', align: 'left' },
  { name: 'nextNumber', label: 'Next number', field: 'nextNumber', align: 'left' },
  { name: 'updatedBy', label: 'Changed by', field: 'updatedBy', align: 'left', format: v => v || '—' }
]

const preview = m => {
  const body = String(m.nextValue ?? 0).padStart(m.bodyLength || 0, '0')
  return (m.prefix || '') + body + (m.checkDigit === 'LUHN' ? '·' : '')
}

const fields = [
  { name: 'code', label: 'Code', required: true, uppercase: true, maxlength: 32, mono: true, lockedOnEdit: true,
    hint: 'e.g. ACCOUNT_PREPAID', rules: [v => /^[A-Z0-9_]{1,32}$/.test(v || '') || 'A-Z, 0-9, _ only'] },
  { name: 'name', label: 'Name', required: true, maxlength: 64 },
  { name: 'prefix', label: 'Prefix', uppercase: true, maxlength: 10, mono: true, hint: 'Optional, letters/digits',
    rules: [v => /^[A-Z0-9]{0,10}$/.test(v || '') || 'Letters and digits only'] },
  { name: 'bodyLength', label: 'Digits after prefix', type: 'number', required: true,
    rules: [v => (v >= 4 && v <= 18) || '4 to 18'] },
  { name: 'nextValue', label: 'Next value', type: 'number', required: true,
    hint: m => `Next number: ${preview(m)} · can only move forward`,
    rules: [v => v >= 0 || 'Cannot be negative'] },
  { name: 'checkDigit', label: 'Check digit', type: 'select', required: true,
    hint: m => m.checkDigit === 'LUHN' ? '· in the preview marks the check digit' : '',
    options: [{ label: 'None', value: 'NONE' }, { label: 'Luhn (mod 10), numeric prefix only', value: 'LUHN' }] }
]

const defaults = () => ({ code: '', name: '', prefix: '', bodyLength: 10, nextValue: 1, checkDigit: 'NONE' })
</script>
